clone:
  git:
    image: plugins/git
    depath: 50
    tags: true


pipeline:
    backend:
      image: node:11.13.0
      commands:
        - echo "backend testing"
    front:
      image: node:11.13.0
      when:
        branch: [master, dev]
      commands:
        - yarn install
        - yarn run prod
    
    scp:
      image: appleboy/drone-scp
      host:
        - 206.189.147.149
      username: root
      password: 25946889
      # secret: [ ssh_key ]
      target: /var/www/test
      source: 
        - dist/*

    ssh:
      image: appleboy/drone-ssh
      host:
        - 206.189.147.149
      username: root
      password: 25946889
      secret: [ ssh_key ]
      script:
        - echo "Hi login"
        - ls -al /var/www/test



