clone:
  git:
    image: plugins/git
    depath: 50
    tags: true


pipeline:
    backend:
      image: node:11.13.0
      secrets: [ ssh_key ]
      commands:
        - echo $SSH_KEY

    front:
      image: node:11.13.0
      when:
        branch: [ master, dev ]
      commands:
        - yarn install
        - yarn run prod

    scp:
      image: appleboy/drone-scp
      host:
        - 206.189.147.149
      port: 22
      username: stan
      secrets: [ ssh_key ]
      target: /var/www/test
      source: 
        - "server.js"
        - "*.json"
        - "docker-compose.yml"
        - Dockerfile
        - dist
        - server
        - node_modules
      when:
        branch: [ master, dev ]
    back-ssh:
      image: appleboy/drone-ssh
      host:
        - 206.189.147.149
      port: 22
      username: stan
      secrets: [ ssh_key ]
      script:
        - rm -rf /var/www/personalSite && mkdir -p /var/www/personalSite
        - cp -r /var/www/test/* /var/www/personalSite
        - cd /var/www/personalSite/server && docker-compose up -d
        - docker restart server_maoweb mongo
    front-ssh:
      image: appleboy/drone-ssh
      host:
        - 206.189.147.149
      port: 22
      username: stan
      secrets: [ ssh_key ]
      script:
        - cd /var/www/personalSite && pm2 restart server.js



