---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

# clone:
#   disable: true

steps:
- name: publish
  image: plugins/docker
  repo: tonytonitone/react
  tags: [ latest ]
  dockerfile: Dockerfile
  secrets: [ docker_username, docker_password ]