version: "3"


services:
  maoweb:
    build: .
    # stdin_open: true
    ports:
      - "9001:9001"
    tty: true
    links:
      - database
    depends_on:
      - database
    
  database:
    image: mongo
    ports: 
      - "27017:27017"