enum SkillType {
  FRONT_END
  BACK_END
  DATA_BASE
  TEST
}

type Profile {
  id: Int
  skill: [Skill]
}

type Skill {
  name: String!
  score: Int!
  type: SkillType!
}

input NewProfileInput {
  type: SkillType!
  name: String!
  score: Int!
}

extend type Query {
  profiles: Profile!
}

type Mutation {
  newProfile(input: NewProfileInput!): Profile!
}